// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/alga/add": {
            "post": {
                "description": "添加藻类图片数据",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "aldb"
                ],
                "summary": "AddAlga",
                "parameters": [
                    {
                        "example": "640fd8c403c8e6ead93ea295",
                        "description": "数据集ID",
                        "name": "riverId",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "example": "64117bf11c55d4d364da3828",
                        "description": "图片ID",
                        "name": "name",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "example": "https://aldb.obs.cn-east-3.myhuaweicloud.com/img/1679155481苹果_2014-12-27_11-16-14.jpg",
                        "description": "图片连接",
                        "name": "src",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{code, msg, data}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/alga/addMul": {
            "post": {
                "description": "批量添加藻类图片数据",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "aldbs"
                ],
                "summary": "AddAlgas",
                "responses": {
                    "200": {
                        "description": "{code, msg, data}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/alga/all": {
            "get": {
                "description": "获取一个数据集所有图片",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "aldbs"
                ],
                "summary": "getAllAlgas",
                "responses": {
                    "200": {
                        "description": "{code, msg, data}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/alga/anno": {
            "get": {
                "description": "藻类图像获取标注",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "aldb"
                ],
                "summary": "GetAnnotationByAlga",
                "parameters": [
                    {
                        "type": "string",
                        "description": "藻类名称",
                        "name": "alga",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{code, msg, data}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/alga/get": {
            "post": {
                "description": "得到具体藻类图像数据",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "aldb"
                ],
                "summary": "getAlga",
                "responses": {
                    "200": {
                        "description": "{code, msg, data}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/alga/search": {
            "post": {
                "description": "搜索藻类图像",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "aldb"
                ],
                "summary": "SearchAlga",
                "responses": {
                    "200": {
                        "description": "{code, msg, data}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/anno/add": {
            "post": {
                "description": "添加标注",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "aldb"
                ],
                "summary": "AddAnnotation",
                "responses": {
                    "200": {
                        "description": "{code, msg, data}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/anno/delete": {
            "get": {
                "description": "删除标注",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "aldb"
                ],
                "summary": "DeleteAnnotation",
                "responses": {
                    "200": {
                        "description": "{code, msg, data}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/river/add": {
            "post": {
                "description": "添加河流数据",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "aldb"
                ],
                "summary": "AddRiver",
                "parameters": [
                    {
                        "example": "aaa",
                        "description": "用户邮箱",
                        "name": "userEmail",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "example": "test",
                        "description": "数据集名称ID",
                        "name": "name",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "example": "testing",
                        "description": "数据集描述",
                        "name": "description",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{code, msg, data}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/river/all": {
            "post": {
                "description": "获取用户所有数据集",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "aldb"
                ],
                "summary": "GetRivers",
                "responses": {
                    "200": {
                        "description": "{code, msg, data}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/river/info": {
            "get": {
                "description": "获取所有数据集藻类列表数据",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "aldb"
                ],
                "summary": "GetRiverInfo",
                "parameters": [
                    {
                        "example": "640fd8c403c8e6ead93ea295",
                        "description": "数据集ID",
                        "name": "RiverID",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{code, msg, data}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/tag/add": {
            "post": {
                "description": "添加标签数据",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "aldb"
                ],
                "summary": "AddTag",
                "responses": {
                    "200": {
                        "description": "{code, msg, data}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/tag/all": {
            "get": {
                "description": "获取所有标签数据",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "aldb"
                ],
                "summary": "GetTags",
                "responses": {
                    "200": {
                        "description": "{code, msg, data}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/user/all": {
            "get": {
                "description": "获取所有用户信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "aldb"
                ],
                "summary": "GetUsers",
                "responses": {
                    "200": {
                        "description": "{code, msg, data}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/user/delete": {
            "get": {
                "description": "删除用户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "aldb"
                ],
                "summary": "DeleteUser",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户邮箱",
                        "name": "email",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{code, msg, data}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/user/info": {
            "get": {
                "description": "获取用户信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "aldb"
                ],
                "summary": "GetUser",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户邮箱",
                        "name": "email",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{code, msg, data}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/user/pwd": {
            "post": {
                "description": "修改用户密码",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "aldb"
                ],
                "summary": "ChangePassword",
                "responses": {
                    "200": {
                        "description": "{code, msg, data}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/user/update": {
            "post": {
                "description": "修改用户信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "aldb"
                ],
                "summary": "UpdateUser",
                "responses": {
                    "200": {
                        "description": "{code, msg, data}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "127.0.0.1:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Aldb Example API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
