// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Anno: typeof import('./components/Anno.vue')['default']
    Annotaion: typeof import('./components/Annotaion.vue')['default']
    CopyRight: typeof import('./components/CopyRight.vue')['default']
    Drawer: typeof import('./components/Drawer.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Grant: typeof import('./components/Grant.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    IEpEditPen: typeof import('~icons/ep/edit-pen')['default']
    IEpElementPlus: typeof import('~icons/ep/element-plus')['default']
    IEpLock: typeof import('~icons/ep/lock')['default']
    IEpPriceTag: typeof import('~icons/ep/price-tag')['default']
    IEpUser: typeof import('~icons/ep/user')['default']
    ImageLabel: typeof import('./components/image-label.vue')['default']
    Main: typeof import('./components/Main.vue')['default']
    NewDatasetDialog: typeof import('./components/NewDatasetDialog.vue')['default']
    NewTagsetDialog: typeof import('./components/NewTagsetDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShareDatasetDialog: typeof import('./components/ShareDatasetDialog.vue')['default']
    Upload: typeof import('./components/Upload.vue')['default']
    UploadDialog: typeof import('./components/UploadDialog.vue')['default']
  }
}

export {}
